
GET http://localhost:3000/us.representatives/

###

GET http://localhost:3000/us.senators

###

GET http://localhost:3000/us.representatives/VA

###

GET http://localhost:3000/us.senators/TX

###

POST /us.senators HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "bioguideid": "S000008",
  "firstname": "Emily",
  "lastname": "Clark",
  "birthday": "1982-04-10",
  "gender": "F",
  "title_long": "Senator",
  "senator_class_label": "Class II",
  "senator_rank_label": "Junior",
  "party": "Democrat",
  "state": "CA"
}

###

POST /us.representatives HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "bioguideid": "R000123",
  "firstname": "John",
  "lastname": "Doe",
  "birthday": "1980-05-15",
  "gender": "M",
  "title_long": "Representative",
  "party": "Democrat",
  "state": "CA"
}

###
#Usando o bioguideid do último representante em Current_US_Representatives.json

PUT /us.representatives/W000831 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "firstname": "Jane",
  "lastname": "Doe",
  "party": "Republican",
  "state": "CA"
}




