
GET http://localhost:3000/us.representatives/

###

GET http://localhost:3000/us.senators

###

GET http://localhost:3000/us.representatives/VA

###

GET http://localhost:3000/us.senators/TX

###

POST /us.senators HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "bioguideid": "S000007",
  "firstname": "David",
  "lastname": "Brown",
  "birthday": "1975-08-20",
  "gender": "M",
  "title_long": "Senator",
  "senator_class_label": "Class I",
  "party": "Republican",
  "state": "FL"
}



